### ISSUE TITLE
OR queries not returning correct results

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/postgresql#64] opened 2018-05-16 20:55 UTC
When running an or query
```swift
category.menuItems.query(on: req).filter(\MenuItem.enabled == true) .group(.or, closure: { builder in
    try builder.filter(\MenuItem.availability == Availability.everyday) // everyday = 0
    try builder.filter(\MenuItem.availability == Availability(weekday: clientCurrentTime.weekday)) // clientCurrentTime.weekday = 1-7
}).paginate(for: req)
```
no results are returned. The returned SQL is 
```sql
SELECT * FROM "menu_items" 
JOIN "category_menu_items" ON "menu_items"."id" = "category_menu_items"."menuItemId" 
WHERE ("category_menu_items"."categoryId" = $1 
    AND "menu_items"."enabled" = $2 
    AND ("menu_items"."availability" = $3 
        OR "menu_items"."availability" = $4)
    ) 
ORDER BY "menu_items"."createdAt" 
DESC LIMIT 10 OFFSET 0 
["UUID (binary) ièbL\u{1A}$J(übøQú³)", "BOOLEAN (binary) \u{01})", "CHAR (binary) \0)", "CHAR (binary) \u{03})"]
```

When performing the query and `clientCurrentTime.weekday` returns a value that is present on one of the models, then it is returned. 

I was doing something similar to this with Vapor 2 which leads me to think there is something wrong here. 

The expected result is menu items with the `availability` value of `0` or `4` should be returned, but in this case, results are only returned if the second condition is met. 

I am using enums, so issue #61 could partly be the cause here too.

**Comment by calebkleveter** [comment] 2018-05-16 20:59
I have been able to reproduce this issue for a while. Using MySQL, so I think this is a Fluent thing, not necessarily driver specific.

**Comment by anthonycastelli** [comment] 2018-05-16 21:00
Yeah, that sounds more like it if you're having issues with MySQL too.

**Comment by rafiki270** [comment] 2018-05-16 21:02
@anthonycastelli have you tried to execute the query directly on the DB without vapor?

**Comment by rafiki270** [comment] 2018-05-16 21:04
if it's fluent we should create an issue there

**Comment by anthonycastelli** [comment] 2018-05-16 21:05
With all the strange byte encoding from enums, I didn't have any luck with a raw query

**Comment by rafiki270** [comment] 2018-05-16 21:06
well, you can assume the representation is correct, try to run the query with just values and see if you get data ... if so, its the way the data is represented, if not, it's probably a bug in fluent compiling the query

**Comment by anthonycastelli** [comment] 2018-05-16 21:09
Right, I have. No dice

**Comment by rafiki270** [comment] 2018-05-16 21:12
try to get it to work manually by modifying the query to give you the data you need, we can then reverse engineer the query into fluent

**Comment by calebkleveter** [comment] 2018-05-16 21:29
@anthonycastelli Do OR statements work for you if you do something simple like:

```swift
try User.query(on: request).group(.or) { query in
    try query.filter(\.firstname == "Anthony")
    try query.filter(\.lastname == ""Castelli")
}
```

Because even for that my ORs break. What I mean is problem is deeper than the encoding.

**Comment by anthonycastelli** [comment] 2018-05-16 21:34
Thats where it gets interesting for me. 

This fails
```swift
return try MenuItem.query(on: req).group(.or) { builder in
    try builder.filter(\MenuItem.availability == Availability.everyday)
    try builder.filter(\MenuItem.availability == Availability(weekday: clientCurrentTime.weekday))
}.paginate(for: req)
```

But this succeeds. 

```swift
return try MenuItem.query(on: req).group(.or) { builder in
    try builder.filter(\MenuItem.name == "PAW Item")
    try builder.filter(\MenuItem.name == "Test Item")
}.paginate(for: req)
```

Thats why I'm leaning towards to encoding issue for me

**Comment by calebkleveter** [comment] 2018-05-16 21:41
Maybe mine is just a MySQL error then 🤔.

**Comment by tanner0101** [comment] 2018-06-02 05:09
@anthonycastelli are you getting an error? Better explaining the expected vs. actual result would help me understand this issue 👍

**Comment by tanner0101** [comment] 2018-07-25 23:04
Closing here in favor of https://github.com/vapor/fluent-postgresql/issues. I will add a test there to ensure this is working, thanks!

**Closed by tanner0101** 2018-07-25 23:04 UTC
Labels: bug
